### ISSUE TITLE
Strat Search

### ISSUE THREAD

**Issue by cecilia-sanare** [rain-cafe-xiv/silvy#2]
### Tasks

- [ ] Come up with a more official name (maybe just "Search" or "Community"?)
- [ ] Ability to view all public strats
- [ ] Sort by most liked or newest (most liked being default)
